### ISSUE TITLE
[Features] Improve UX

### ISSUE THREAD

**Issue by tbarsen85** [roflcoopter/viseron#575]
Creating this to track my tasks and for awareness to others. Comments/suggestions are welcomed.

Creating new pages that will have a GUI to edit settings, execute commands, and view logs for an easier/better user experience. Additional tasks may be added, just setting the ground work now.

Users Page (New)
- [ ] Add section to manage users and set permissions.  #514

Settings - Cameras Page (New)
- [ ]  Add ability to create/manage cameras with GUI. _Pending migration from `voluptuous` schemas to `pydantic` schemas_

System Page (New)
- [ ] Move current Configuration page into the System page under Advanced section to still allow manually editing the `config.yaml` file.
- [ ] Have system related settings such as Webserver Debug toggle and commands such as Restart,etc
- [ ] Add notification section to manage MQTT.
- [ ] Add other alerting systems(Pushover,etc)
- [ ] Add section to view logs with GUI.  #475 

Cameras Page
- [ ] Add live view and set as default behaviour. #442 
- [ ] Add ability to filter view & alert list by camera group
- [ ] Add side bar containing list of recent camera alerts

**Comment by roflcoopter** [comment]
Awesome list!

I have not started any work on #514 so you are free to take that one.
I am currently building CodeProject.AI support for object detection and other domains, so no UI stuff for me currently.

My plan is to start working on 24/7 recordings when i am done with that.

Also regarding managing cameras in the GUI, i think you should hold off on that one for a while.
I have plans to migrate all `voluptuous` schemas to `pydantic` schemas, which will allow us to generate JSON-schemas which can then be converted into TypeScript types for easy validation in the GUI.
Otherwise we would have to duplicate all the validation logic and keep frontend/backend in sync.

I am also planning to mive to `FastAPI` instead of `tornado` since `FastAPI` is also using `pydantic`, keeping everything more uniform.
A bonus of `FastAPI` is that the OpenAPI spec can be generated as well, today i dont have any documentation of the API sadly

**Comment by tbarsen85** [comment]
Great, thanks for that information.

> Also regarding managing cameras in the GUI, i think you should hold off on that one for a while.
> I have plans to migrate all `voluptuous` schemas to `pydantic` schemas, which will allow us to generate JSON-schemas which can then be converted into TypeScript types for easy validation in the GUI.

Yes I will definitely hold off then, that would make it a lot easier to work with.

**Comment by spupuz** [comment]
any update on this?
would be awesome a timeline view for recordings

**Comment by roflcoopter** [comment]
I am still working hard on the timeline and 24/7 recordings.
It is a lot of work and the UI part has proven to be much harder than i anticipated.
It is very hard to to this as a solo developer during only my free time as you might imagine.
You can watch the PR #619 to follow the progress.

Will post some screenshots there so you can see where i am at currently!

@tbarsen85 are you still interested in contributing?

**Comment by spupuz** [comment]
> I am still working hard on the timeline and 24/7 recordings. It is a lot of work and the UI part has proven to be much harder than i anticipated. It is very hard to to this as a solo developer during only my free time as you might imagine. You can watch the PR #619 to follow the progress.
> 
> Will post some screenshots there so you can see where i am at currently!
> 
> @tbarsen85 are you still interested in contributing?

You are doing an amazing work I'm not a developer, differently I would be happy to help.

**Comment by spupuz** [comment]
eventually take a look to scrypted.app and https://demo.scrypted.app/#/demo looks fantastic.

**Comment by roflcoopter** [comment]
Closing due to inactivity.
